CREATE DATABASE IF NOT EXISTS %DB% CHARACTER SET = 'UTF8';

DROP TABLE IF EXISTS  %DB%.Books;
CREATE TABLE %DB%.Books ( 
id BIGINT UNSIGNED NOT NULL,
coverprice DOUBLE(18,2) NOT NULL, 
isbn VARCHAR(255) NOT NULL,
bookname VARCHAR(255) NOT NULL,
category VARCHAR(255) NOT NULL, 
discount DOUBLE(18,2) NOT NULL) Engine = columnstore;


DROP TABLE IF EXISTS  %DB%.Covers;
CREATE TABLE %DB%.Covers ( 
id INTEGER NOT NULL, 
image LONGBLOB NOT NULL) Engine = columnstore;

DROP TABLE IF EXISTS  %DB%.TransactionTypes;
CREATE TABLE %DB%.TransactionTypes ( 
id BIGINT UNSIGNED NOT NULL, 
tr_type VARCHAR(50) NOT NULL,
PRIMARY KEY(id)) Engine = InnoDB;


DROP TABLE IF EXISTS  %DB%.Cards;
CREATE TABLE %DB%.Cards ( 
card_id BIGINT UNSIGNED NOT NULL,
customer_id BIGINT UNSIGNED NOT NULL, 
card_nm VARCHAR(255) NOT NULL,
card_type VARCHAR(255) NOT NULL,
discount VARCHAR(255) NOT NULL, 
points DOUBLE(18,2) NOT NULL) Engine = columnstore;


DROP TABLE IF EXISTS  %DB%.Emails;
CREATE TABLE %DB%.Emails ( 
email_id BIGINT UNSIGNED NOT NULL,
customer_id BIGINT UNSIGNED NOT NULL, 
email_adr VARCHAR(255) NOT NULL) Engine = columnstore;

DROP TABLE IF EXISTS  %DB%.Phones;
CREATE TABLE %DB%.Phones ( 
phone_id BIGINT UNSIGNED NOT NULL,
customer_id BIGINT UNSIGNED NOT NULL, 
phone_nm VARCHAR(255) NOT NULL) Engine = columnstore;

DROP TABLE IF EXISTS  %DB%.Addresses;
CREATE TABLE %DB%.Addresses ( 
address_id BIGINT UNSIGNED NOT NULL,
customer_id BIGINT UNSIGNED NOT NULL, 
address VARCHAR(255) NOT NULL) Engine = columnstore;

DROP TABLE IF EXISTS  %DB%.Transactions;
CREATE TABLE %DB%.Transactions ( 
trans_date DATETIME NOT NULL,
order_id BIGINT UNSIGNED NOT NULL,
transaction_id BIGINT UNSIGNED NOT NULL,
price DOUBLE(18,2) NOT NULL, 
discount DOUBLE(18,2) NOT NULL, 
discounted_price DOUBLE(18,2) NOT NULL, 
transaction_type INTEGER NOT NULL,
customer_id BIGINT UNSIGNED NOT NULL) Engine = columnstore;

DROP TABLE IF EXISTS  %DB%.LoyaltyPoints;
CREATE TABLE %DB%.LoyaltyPoints ( 
trans_date DATETIME NOT NULL,
order_id BIGINT UNSIGNED NOT NULL,
card_is BIGINT UNSIGNED NOT NULL,
points INTEGER NOT NULL, 
customer_id BIGINT UNSIGNED NOT NULL) Engine = columnstore;

LOAD DATA LOCAL INFILE '%CSV%books.csv'
INTO TABLE %DB%.Books
CHARACTER
SET UTF8 FIELDS
TERMINATED BY ','
ENCLOSED BY ''''
ESCAPED BY '\\' LINES TERMINATED BY '\n' IGNORE 0 LINES;

LOAD DATA LOCAL INFILE '%CSV%covers.csv'
INTO TABLE %DB%.Covers
CHARACTER
SET UTF8 FIELDS
TERMINATED BY ','
ENCLOSED BY ''''
ESCAPED BY '\\' LINES TERMINATED BY '\n' IGNORE 0 LINES;

LOAD DATA LOCAL INFILE '%CSV%cards.csv'
INTO TABLE %DB%.Cards
CHARACTER
SET UTF8 FIELDS
TERMINATED BY ','
ENCLOSED BY ''''
ESCAPED BY '\\' LINES TERMINATED BY '\n' IGNORE 0 LINES;

LOAD DATA LOCAL INFILE '%CSV%emails.csv'
INTO TABLE %DB%.Emails
CHARACTER
SET UTF8 FIELDS
TERMINATED BY ','
ENCLOSED BY ''''
ESCAPED BY '\\' LINES TERMINATED BY '\n' IGNORE 0 LINES;

LOAD DATA LOCAL INFILE '%CSV%phones.csv'
INTO TABLE %DB%.Phones
CHARACTER
SET UTF8 FIELDS
TERMINATED BY ','
ENCLOSED BY ''''
ESCAPED BY '\\' LINES TERMINATED BY '\n' IGNORE 0 LINES;

LOAD DATA LOCAL INFILE '%CSV%addresses.csv'
INTO TABLE %DB%.Addresses
CHARACTER
SET UTF8 FIELDS
TERMINATED BY ','
ENCLOSED BY ''''
ESCAPED BY '\\' LINES TERMINATED BY '\n' IGNORE 0 LINES;

LOAD DATA LOCAL INFILE '%CSV%transactions.csv'
INTO TABLE %DB%.Transactions
CHARACTER
SET UTF8 FIELDS
TERMINATED BY ','
OPTIONALLY ENCLOSED BY ''''
ESCAPED BY '\\' LINES TERMINATED BY '\n' IGNORE 0 LINES;

LOAD DATA LOCAL INFILE '%CSV%loaylty_points.csv'
INTO TABLE %DB%.LoyaltyPoints
CHARACTER
SET UTF8 FIELDS
TERMINATED BY ','
ENCLOSED BY ''''
ESCAPED BY '\\' LINES TERMINATED BY '\n' IGNORE 0 LINES;



INSERT INTO %DB%.TransactionTypes (id,tr_type) VALUES (1,'Item'), (2,'Discount'),(3,'Shipping');

SELECT CONCAT('Loaded ',COUNT(*),' in Books') as '' FROM %DB%.Books;
SELECT CONCAT('Loaded ',COUNT(*),' in Covers') as '' FROM %DB%.Covers;
SELECT CONCAT('Loaded ',COUNT(*),' in Cards') as '' FROM %DB%.Cards;
SELECT CONCAT('Loaded ',COUNT(*),' in Emails') as '' FROM %DB%.Emails;
SELECT CONCAT('Loaded ',COUNT(*),' in Phones') as '' FROM %DB%.Phones;
SELECT CONCAT('Loaded ',COUNT(*),' in Addresses') as '' FROM %DB%.Addresses;
SELECT CONCAT('Loaded ',COUNT(*),' in Transactions') as '' FROM %DB%.Transactions;
SELECT CONCAT('Loaded ',COUNT(*),' in LoyaltyPoints') as '' FROM %DB%.LoyaltyPoints;