language: bash
services: docker
matrix:
  include:
    - env:
        VERSION=columnstore
        TYPE=docker-compose
    - env:
        VERSION=columnstore_jupyter
        TYPE=docker
    - env:
        VERSION=columnstore_sandbox
        TYPE=docker
    - env:
        VERSION=columnstore_zeppelin
        TYPE=docker-compose
    - env:
        VERSION=tx_sandbox
        TYPE=docker

install:
  - git clone https://github.com/mariadb-corporation/mariadb-docker-images ~/mariadb-docker-images

before_script:
  - env | sort
  - cd "$VERSION"
  - image="mariadb-columnstore-docker:$VERSION"
  - if [ "$TYPE" = "docker" ]; then echo "docker build"; else echo "docker-compose build"; fi
  - if [ "$TYPE" = "docker-compose" ]; then echo "docker-compose build"; else echo "docker build";fi


script:
  - if [ "$TYPE" = "docker" ]; then travis_retry docker build -t "$image" .; ~/mariadb-docker-images/test/run.sh "$image"; fi
  - if [ "$TYPE" = "docker-compose" ]; then travis_retry docker-compose up --build;; ~/mariadb-docker-images/test/run.sh "$image"; fi

after_script:
  - if [ "$TYPE" = "docker" ]; then docker images; fi
  - if [ "$TYPE" = "docker-compose" ]; then docker-compose images; fi