language: bash
services: docker
env:
  - VERSION=columnstore
  - TYPE=docker-compose
#  - VERSION=columnstore_jupyter #broken
  - VERSION=columnstore_sandbox
  - TYPE=docker
  - VERSION=columnstore_zeppelin
  - TYPE=docker-compose
  - VERSION=tx_sandbox
  - TYPE=docker

install:
  - git clone https://github.com/mariadb-corporation/mariadb-docker-images ~/mariadb-docker-images

before_script:
  - env | sort
  - cd "$VERSION"
  - image="mariadb-columnstore-docker:$VERSION"
  - if [ "$TYPE" = "docker" ]; echo "docker build"; fi
  - if [ "$TYPE" = "docker-compose" ]; echo "docker-compose build" fi


script:
  - if [ "$TYPE" = "docker" ]; then travis_retry docker build -t "$image" .; ~/mariadb-docker-images/test/run.sh "$image"; fi
  - if [ "$TYPE" = "docker-compose" ]; then travis_retry docker-compose up --build; fi

after_script:
  - docker images