language: bash
services: docker
env:
  - VERSION=columnstore
#  - VERSION=columnstore_jupyter #broken
#  - VERSION=columnstore_sandbox
  - VERSION=columnstore_zeppelin
#  - VERSION=tx_sandbox

install:
  - git clone https://github.com/mariadb-corporation/mariadb-docker-images ~/mariadb-docker-images

before_script:
  - env | sort
  - cd "$VERSION"
  - image="mariadb-columnstore-docker:$VERSION"

script:
  - travis_retry docker-compose up --build

after_script:
  - docker-compose images