version: "2"

services:
  columnstore:
    hostname: server
    build: ../columnstore_sandbox
    ports:
      - "3306:3306"
    # volumes:
    #   - ./columnstore_um1:/docker-entrypoint-initdb.d

  zeppelin:
    hostname: zeppelin
    build: ../columnstore_zeppelin
  
    ports:
      - "8080:8080"
    links:
      - columnstore
    volumes:
    - ../columnstore_zeppelin/notebook:/zeppelin/notebook