version: "2"

services:
  columnstore:
    hostname: columnstore
    build: ../columnstore
    ports:
      - "3306:3306"
  zeppelin:
    hostname: zeppelin
    build: ../columnstore_zeppelin
    ports:
      - "8080:8080"
    links:
      - columnstore
    volumes:
    - ../columnstore_zeppelin/notebook:/zeppelin/notebook