language: bash
services: docker
env:
  - TAG=mariadb/columnstore
  - LOCATION=../columnstore
  - VERSION=columnstore_sandbox


install:
  - git clone https://github.com/mariadb-corporation/mariadb-docker-images ~/mariadb-docker-images

before_script:
  - docker build -t "$from" ../columnstore
  - env | sort
  - cd "$VERSION"
  - image="mariadb-columnstore-docker:$VERSION"

script:
  - travis_retry docker build -t "$image" .
  - ~/mariadb-docker-images/test/run.sh "$image"

after_script:
- docker images